### ISSUE TITLE
Exceedance frequencies for 2011 differ from reference dataset

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares-research/kenmerkendewaarden#154]
The overschrijdingsfrequenties derived within KWK are a combination of weibul-fit over measurement data for high frequencies and HYDRA-data for low-frequencies. The latter are still to be updated, differences are expected. However, the first ones (high frequencies) also differ from reference datasets. This is unexpected.

Some details:
- the examples in this issue focus on higher frequencies (5 times per year to once per 10 years)
- the `Gele-boekje-2016` values correspond to the exceedance frequencies from [“Kenmerkende waarden getijgebied 2011" (juli, 2013)](https://open.rijkswaterstaat.nl/@164322/kenmerkende-waarden-getijgebied-2011)
- therefore, the different values for `KWK-python` and `Gele-boekje-2016` both cover the exceedance waterlevel data up to 1-1-2011

Some stations from south to north:
```python
import os
import pandas as pd
import matplotlib.pyplot as plt
plt.close('all')
import hatyan
import kenmerkendewaarden as kw # pip install git+https://github.com/Deltares-research/kenmerkendewaarden

# set logging level to INFO to get log messages
import logging
logging.basicConfig() # calling basicConfig is essential to set logging level for sub-modules
logging.getLogger("kenmerkendewaarden").setLevel(level="WARNING")

dict_geleboek = {
    "VLISSGN": [305, 320, 335, 350, 365, 385],
    "HOEKVHLD": [210, 230, 245, 260, 285, 300],
    "DENHDR": [165, 190, 210, 230, 255, 275],
    "HARLGN": [225, 255, 280, 305, 330, 355],
    "SCHIERMNOG": [225, 250, 275, 295, 320, 340],
    }
station_list = dict_geleboek.keys()
freq_list = [5, 2, 1, 0.5, 0.2, 0.1]

year_slotgem = 2011

dir_base = r'p:\11210325-005-kenmerkende-waarden\work'
dir_meas = os.path.join(dir_base,'measurements_wl_18700101_20240101')

nap_correction = False
drop_duplicates = True

for current_station in station_list:
    print(f'starting process for {current_station}')
    # extremes are used for slotgemiddelden, havengetallen, overschrijding
    df_ext_12345_all = kw.read_measurements(dir_output=dir_meas, station=current_station, extremes=True,
                                      nap_correction=nap_correction, drop_duplicates=drop_duplicates)
    if df_ext_12345_all is None:
        raise ValueError(f"missing data for {current_station}")
    
    # convert 12345 to 12 by taking minimum of 345 as 2 (laagste laagwater)
    df_ext_all = hatyan.calc_HWLW12345to12(df_ext_12345_all)
    
    # crop measurement data to (excluding) year_slotgem
    df_ext_todate = df_ext_all.loc[:str(year_slotgem-1)]
    
    # 1. Exceedance
    dist_exc = kw.calc_overschrijding(df_ext=df_ext_todate, rule_type=None, rule_value=None, 
                                      clip_physical_break=True,
                                      interp_freqs=freq_list)
    
    df = pd.DataFrame(index=freq_list)
    df["KWK-python"] = dist_exc['geinterpoleerd'].round().astype(int)
    df_geleboek = pd.Series(index=freq_list, data=dict_geleboek[current_station])
    df["Gele-boekje-2016"] = df_geleboek
    print(df)
    # fig, ax = kw.plot_overschrijding(dist_exc)
    # ax.set_ylim(0,550)
```

Prints (with data retrieved in April 2025, same results with data retrieved after DDL update of 8 August 2025):
```
starting process for VLISSGN
     KWK-python  Gele-boekje-2016
5.0         291               305
2.0         308               320
1.0         323               335
0.5         337               350
0.2         356               365
0.1         370               385
starting process for HOEKVHLD
     KWK-python  Gele-boekje-2016
5.0         193               210
2.0         214               230
1.0         230               245
0.5         247               260
0.2         268               285
0.1         283               300
starting process for DENHDR
     KWK-python  Gele-boekje-2016
5.0         159               165
2.0         185               190
1.0         204               210
0.5         223               230
0.2         246               255
0.1         263               275
starting process for HARLGN
     KWK-python  Gele-boekje-2016
5.0         217               225
2.0         249               255
1.0         272               280
0.5         294               305
0.2         321               330
0.1         341               355
starting process for SCHIERMNOG
     KWK-python  Gele-boekje-2016
5.0         219               225
2.0         248               250
1.0         271               275
0.5         292               295
0.2         317               320
0.1         334               340
```

With previously retrieve data (December 2024?), most values were the same, but DENHDR had different values:
```
Den Helder:
freq KWK-python Gele-boekje-2016
5	149	165
2	172	190
1	192	210
0.5	210	230
0.2	233	255
0.1	249	275
```

The westerly stations seem to show a shift in the frequency table (row-wise), but the northerly stations not per se. The differences can be caused by:
- According to [“Kenmerkende waarden kustwateren en grote rivieren (2013)”](https://open.rijkswaterstaat.nl/open-overheid/onderzoeksrapporten/@44612/kenmerkende-waarden-kustwateren-grote), all values were rounded to 5 cm so that explains part of the differences
- The KWK-python values above are slightly closer to the Gele-boekje-2016 values than reported for KWK-overschrijding in 2020 (n:\Projects\11205000\11205232\C. Report - advise\007 - Kenmerkende waarden RMM\11205232-007-ZKS-0003_v0.1-Kenmerkende Waarden Rijn-Maasmonding - Over- en Onderschrijdingsfrequenties.docx). This is probably because the data is more complete than back then. However, the KWK-python values are still quite far off the reference Gele-boekje-2016, even if it is less far away than reported in 2020.
- excluding measurements before 1998 (as suggested in the 2020 report) influences the resulting values, but not for the better for all frequencies (mixed better/worse).

**Update 18 August 2025**
["Kenmerkende waarden getijgebied 2011" (juli, 2013)](https://open.rijkswaterstaat.nl/@164322/kenmerkende-waarden-getijgebied-2011) describes the method used in chapter 6.3. This states "de correctie voor de trend (delta-trend): het slotgemiddelde 2011.0 minus de waarde van de gemiddelde hoogwaterstand in het betrokken jaar van de hoogwaterstand volgens de PLSS-trendlijn;". Correcting the HW timeseries with delta-trend is tested with the following code (add right before the call to `kw.calc_overschrijding` in the code above, or use new `correct_trend=True` argument implemented in branch):
```python
    # correct all years with delta-trend: slotgemiddelde minus yearly mean
    # chapter 6.3 of kenmerkende_waarden_kustwateren_en_grote_rivieren.pdf
    slotgemiddelden_valid = kw.calc_slotgemiddelden(df_meas=df_ext_todate, df_ext=df_ext_todate)
    slotgem_corr = slotgemiddelden_valid["HW_model_fit"].iloc[-1] - slotgemiddelden_valid["HW_model_fit"].iloc[:-1]
    df_ext_corr = df_ext_todate.copy()
    for year in slotgem_corr.index:
        corr_val = slotgem_corr.loc[year]
        import numpy as np
        if np.isnan(corr_val):
            continue
        df_ext_corr.loc[str(year), "values"] += corr_val
    df_ext_todate = df_ext_corr.copy()
```
Resulting indeed in exceedance frequencies that correspond much better to the validation data (preliminary results, final implementation gives different results):
```
starting process for VLISSGN
     KWK-python  Gele-boekje-2016
5.0         306               305
2.0         323               320
1.0         337               335
0.5         351               350
0.2         370               365
0.1         385               385
starting process for HOEKVHLD
     KWK-python  Gele-boekje-2016
5.0         208               210
2.0         230               230
1.0         246               245
0.5         263               260
0.2         284               285
0.1         300               300
starting process for DENHDR
     KWK-python  Gele-boekje-2016
5.0         168               165
2.0         195               190
1.0         213               210
0.5         231               230
0.2         255               255
0.1         273               275
starting process for HARLGN
     KWK-python  Gele-boekje-2016
5.0         234               225
2.0         266               255
1.0         289               280
0.5         311               305
0.2         338               330
0.1         356               355
starting process for SCHIERMNOG
     KWK-python  Gele-boekje-2016
5.0         224               225
2.0         254               250
1.0         275               275
0.5         296               295
0.2         321               320
0.1         340               340
```

This also decreases the difference between the Hydra line (for DENHDR and VLISSIGN they almost touch). Additionally, correcting the timeseries for NAP-2005 only shows 2 mm difference, so this is much less significant.

Todo:
- [x] implement automatic correction with slotgemiddelden (different for HW/LW), including it in `kw.calc_overschrijding()` also requires `min_coverage` parameter.
- [x] allow for passing `df_meas=None` to `kw.calc_slotgemiddelden()`
- [x] split for HW/LW by making `calc_slotgemiddelden()` modular, currently the entire df_ext gets corrected with the HW or LW trend and that is not correct (and too complex) >> instead correct with mean HW/LW trend
- [x] apply trendcorrection per timestep instead of per year
- [x] investigate difference between this correction and `rule_type="linear"` (also requires `rule_value=0.3` for HOEKVHLD). Domhof (2011, 11205232-007-ZKS-0003 overschrijding) mentions some example riverine stations in Table 3.3 (Chapter 2.3), can this method be aligned with coastal stations? >> rule_type=linear is hard-coded, this trend correction is automated, otherwise comparable. >> follow-up issue https://github.com/Deltares-research/kenmerkendewaarden/issues/252
- [x] `kw.calc_overschrijding()` has unused `rule_type="break"` and `clip_physical_break`, drop the first option in favor of the latter. This also makes it possible to correct both for a trend and apply a break. The `apply_trendanalysis()` only has added value to see the difference between unfiltered and filtered in a single figure, but this is not super important. >> follow-up issue https://github.com/Deltares-research/kenmerkendewaarden/issues/252
- [x] add/update testcase
- [x] error again on warnings in pytest, was temporarily commented
- [x] update whatsnew
- [x] validate results for DENHDR or HOEKVHLD (HW/LW) and HARLGN (since those values were still significantly off with the POC results) >> values for all stations are closer to the values in the gele boekje when applying automatic trendcorrection. Also, for all stations (except SCHIERMNOG) exceedance frequency lines now align better to the lines from the hydra database.
- [x] maybe remove check for nans in compute_trend_peryear(), first test by updating the KWK_process.py script and running for all stations (including check of results)
- [x] plot_slotgemiddelden crashes when df_meas was not provided to calc_slotgemiddelden, fix this and uncomment lines in test
- [x] consider supplying new preliminary dataset to RWS >> not now, but noted in #239 that fixing this issue results in significant changes in the result.
