### ISSUE TITLE
Link to Python API for hydra exceedance frequencies

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares-research/kenmerkendewaarden#155]
Currently manually extracting HYDRA data:
- [ ] currently manually extracting exceedance frequencies from Hydra-NL: https://github.com/Deltares-research/kenmerkendewaarden/issues/107. However, the current Hydra-NL freqs are significantly different than the ones used before (csv) and further away from the measurements, why? The latter is mainly relevant for HOEKVHLD, so this might also just be an exception.
- [ ] databases WBI2017 (zichtjaar 2023) are available [online via STACK](https://fbwvl.stackstorage.com/s/cQJwECwRv88jqsc/nl/files/36653)
- [ ] avoid need for manual extraction and p-drive link for HYDRA-NL data by moving to HYDRA-RING Python API
- [ ] HYDRA-RING is executable, so this can be called by using database as input, but requires sqlite database (which requires quite some work to set up properly). In 2024 there will be worked on a HYDRA-RING Python API/wrapper, which makes this easier (https://issuetracker.deltares.nl/browse/HRING-2043)
- [ ] prevent the need to supply dict with 'Hydra-NL' distribution, this is typo-risky

Wishlist for HYDRA-RING Python API:
- [ ] retrieve results based on user-defined xy-coordinates, API gets values nearest locationid from correct database automatically (including a max_distance parameter)
- [ ] retrieve results for a user-defined list of frequencies
- [ ] retrieve values relevant for kw 2011/2021/etc. This depends on "zichtjaar" 2011(?)/2023/2035/etc and SLR choices
- [ ] include model uncertainty (or not)
- [ ] pip installable with light dependencies (single package that does not require separate artifacts)
- [ ] no need to manually download databases from somewhere
- [ ] single line/request to retrieve list of exceedance frequency values for a particular station

**Comment by veenstrajelmer** [comment]
New information after Hydra work done in December 2024:
- available on [github](https://github.com/Deltares/Hydra-Ring/tree/main/wrapper), specifically the [readme.md](https://github.com/Deltares/Hydra-Ring/blob/main/wrapper/readme.md) and [water_level_calculations.ipynb](https://github.com/Deltares/Hydra-Ring/blob/main/wrapper/HydraRing.PWrapper.Notebooks/water_level_calculations.ipynb) seems useful
- wheels available on [teamcity](https://dpcbuild.deltares.nl/buildConfiguration/Boi_HydraRing_HydraRingTrunk_PythonBuildAndTests_CreatePythonWheelNew?tag=24.1.3) (install with `pip install Hydra_Ring-24.1.3-py3-none-any.whl`)
- binaries available on [teamcity](https://dpcbuild.deltares.nl/buildConfiguration/Boi_HydraRing_HydraRingTrunk_BasicBuildsAndTestsOneAPI_Build?tag=24.1.2) (deliverables.zip) (set `project.settings.hydraring_path` to the unzipped directory)
- in water_level_calculations.ipynb, `project.settings.hlcd_path` should point to hydraulic database file as in [example](https://github.com/Deltares/Hydra-Ring/blob/8c124f16d8f29224cfd9accb7c5ef3da8d7b50d2/wrapper/HydraRing.PWrapper.Test/test_range.py#L29). This is not mentioned in [readme.md](https://github.com/Deltares/Hydra-Ring/blob/main/wrapper/readme.md). However, when not supplying it, there is no error but there should be, since `project.h_design=nan` and `project.design_point=None`
- there is a filter to find the location_id to a specific xy coordinate: [selection_of_locations.ipynb](https://github.com/Deltares/Hydra-Ring/blob/main/wrapper/HydraRing.PWrapper.Notebooks/selection_of_locations.ipynb)
- retrieving a range of return periods is also possible: [design_calculations_range_return_periods.ipynb](https://github.com/Deltares/Hydra-Ring/blob/main/wrapper/HydraRing.PWrapper.Notebooks/design_calculations_range_return_periods.ipynb)

This makes it possible to extract what we need with:
```python
from hydra_ring import HydraringProject, ModelType, IntegrationTechnique, CalculationTechnique, Submechanism
from hydra_ring import FORMstartMethods, UncertaintyChoice, CalculationType
from hydra_ring import DesignTable
import matplotlib.pyplot as plt
plt.close("all")
import numpy as np

# We create a project using the `HydraringProject()` class.
project = HydraringProject()


# ### Defining paths and location
# Next, we specify the location of the artifacts of Hydra-Ring (`hydraring_path`) and the location of the HLCD file (`hlcd_path`).
# Using `save_hydraring_files`, we can choose either to save the input and output files of Hydra-Ring or to remove the files once the calculation is finished.
# We specify the hydraulic location using the `location_id` attribute. 
# The calculation model is set using the `ModelType()` class, in this case we choose the `water_level` attribute.

# TODO: if hydraring_path is not set (or unavailable), project.design_point is None instead of an error
project.settings.hydraring_path = r"c:\Users\veenstra\Downloads\deliverables" # "here path to the binaries folder"
# TODO: cumbersome to have multiple hlcd files, so request a single file for the entire NL
project.settings.hlcd_path = "p:/1230088.019-hydraring/databases/Hydraulic Databases WTI2017 - 16 September 2019 TeamCity/hlcd.sqlite"
project.settings.save_hydraring_files = False
print(f"working dir = {project.settings.working_dir}")
# project.settings.location_id = "14811048" # TODO: if not set, project.design_point is None instead of an error
project.settings.model = ModelType.water_level

def print_loc(loc):
    print(f"Location name: {loc.name}")
    print(f"LocationId: {loc.location_id}")
    print(f"HRDLocationId: {loc.hrd_location_id}")
    print(f"x-coordinate (m): {loc.x}")
    print(f"y-coordinate (m): {loc.y}")
    print(f"Distance (m): {loc.distance}")
    print()

# get location information
# from hydra_ring import Location
# loc = Location("14811048") # TODO: this fails, expects ids like 22 or 19 (project._id ?) not location_id or hrd_location_id
# print_loc(loc)


# get locations close to xy coordinate
xcoord, ycoord = 204082, 429373 # lobith
xcoord, ycoord = 67761.302278, 443678.166279 # hoek van holland
xcoord, ycoord = 156205.893151, 576350.330937 # harlingen
xcoord, ycoord = 30349.826525, 384719.962497 # vlissingen
max_dist_m = 1000
find_closest = False

if find_closest:
    print("finding stations within range")
    # TODO: this works but it is quite slow, is this more complex than a simple KDTree?
    # TODO: can we find all Dutch locations here or only a subset from the db?
    # TODO: how to know the extent of the db (e.g. get all xy coords)
    locations = project.get_locations(xcoord, ycoord, max_dist_m)
    print(f"Number of locations found: {len(locations)}")
    print()
    for loc in locations:
        print_loc(loc)
    
    # find nearest location_id
    distances = [loc.distance for loc in locations]
    loc_idx = np.argmin(distances)
    loc_near = locations[loc_idx]
    
    # TODO: location_id is int as output, but should be str as project input, align
    project.settings.location_id = str(loc_near.location_id)
else:
    # project.settings.location_id = "14811049" # lobith (15 seconds)
    # project.settings.location_id = "1700110" # hoek van holland (>1 minute) # TODO: this station takes quite long, why?
    # project.settings.location_id = "1000465" # harlingen (15 seconds)
    project.settings.location_id = "1500097" # vlissingen (10 seconds)


# ### Defining calculation settings
# The time integration technique is set using the `IntegrationTechnique()` class. Here, we can choose between two options: 
# 
# * `fbc` <br>
# * `nti` <br>
project.settings.integration_technique = IntegrationTechnique.fbc


# The calculation technique is set using the `CalculationTechnique()` class. The available options are: 
# * `form` <br>
# * `directional_sampling` <br>
# * `dsfi` (directional sampling with FORM iterations for the design point) <br>
# * `fdir` (FORM and directional sampling in case of no convergence)
# 
# Using the `FORMstartMethods()` class, we can define the starting method for FORM. The available options are: 
# * `all_zeros` <br>
# * `all_ones` <br>
# * `ray_search` <br>
# * `sphere_search`

# TODO: how to set this such that we can extract the exeedance freqs+levels that are relevant for KWK 2011.0 and 2021.0?
# TODO: also zichtjaar and more as in https://github.com/Deltares-research/kenmerkendewaarden/issues/155
project.settings.numerics[Submechanism.reference_waterlevel].calculation_technique = CalculationTechnique.form
project.settings.numerics[Submechanism.reference_waterlevel].form_start_method = FORMstartMethods.ray_search
project.settings.numerics[Submechanism.reference_waterlevel].form_number_of_iterations = 50
project.settings.numerics[Submechanism.reference_waterlevel].form_relaxation = 0.15
project.settings.numerics[Submechanism.reference_waterlevel].min_directions = 10000
project.settings.numerics[Submechanism.reference_waterlevel].max_directions = 40000
# TODO: officially the settings should be extracted from the configfile and differ per station
# require hlcd file, configfile and location_id to be aligned, otherwise OSError
# would be great if this is less cumbersome
# TODO: also the resulting values do not differ from the defaults, can be checked with
# https://github.com/Deltares/Hydra-Ring/blob/main/wrapper/HydraRing.PWrapper.Notebooks/get_config_settings.ipynb
# project.settings.read_from_config()



# extract a range of return times
project.settings.calculation_type = CalculationType.range_of_return_times
# return_periods = [10, 50, 100, 300, 1000, 3000, 10000, 30000, 100000]
return_periods = [10, 100, 1000, 10000, 100000]
for return_period in return_periods:
    design_value = DesignTable()
    design_value.return_period_design = return_period
    project.settings.design_table.append(design_value)


# Using the `UncertaintyChoice()` class, we can specify which types of
# uncertainties (none, model uncertainty, statistical uncertainty or both)
# should be included in the calculations. The available options are: 
# * `no_uncertainties` <br>
# * `all_uncertainties` <br>
# * `only_model_unc` <br>
# * `only_statistical_unc`

list_unc = [#UncertaintyChoice.no_uncertainties,
            UncertaintyChoice.all_uncertainties,
            ]

fig, ax = plt.subplots()
for unc in list_unc:
    project.settings.uncertainty_choice = unc
    
    # run the project
    project.run()
    
    # # and get the values out
    # for idx, return_period in enumerate(return_periods):
    #     dp = project.fragility_curve.fragility_values[idx].design_point
    #     print(f"Design water level for a return periods of {return_period} years = {project.h_design_values[idx]} m+NAP")
    #     print (f"beta = {dp.reliability_index}")
    #     for alpha in dp.alphas:
    #         print (f"{alpha.variable.name}: alpha = {alpha.alpha}")
    #     print()
    
    # The results are stored in `project.fragility_curve`.
    curve = project.fragility_curve
    
    # The following code reads the specified water levels and their corresponding exceedance probabilities:
    h = []; Pf = []
    for val in curve.fragility_values:
        h.append(val.x)
        Pf.append(val.probability_of_failure)
    ax.semilogx(Pf, h, '-o', label=str(unc))

ax.invert_xaxis()
ax.grid()
ax.set_xlabel("Exceedance probability [1/year]")
ax.set_ylabel("Water level [m+NAP]")
ax.set_title(f"LocationId = {project.settings.location_id}")
ax.legend()
```

Gives:
![Image](https://github.com/user-attachments/assets/ee6facea-3746-4e8a-bfb2-5555dbcfb101)
![Image](https://github.com/user-attachments/assets/8f7daae9-d46d-4e15-abe9-3bbf84254346)

Some improvement ideas for the hydra-ring-api (from TODO in the code above):
- [ ] make Python wheel publicly available on PyPI (and on [STACK](https://fbwvl.stackstorage.com/s/bl2KUAMDG387sUg))
- [ ] include hydra-ring binaries in the python wheel (maybe add option to provide a path to older binaries, but that is mostly interesting for debugging, not per se for the end user)
- [ ] if the `hydraring_path` or the `location_id` (and others) is not set, the package should in my view raise an error, instead of resulting in `project.design_point=None`
- [ ] Would be useful to get the location metadata (x/y/name/etc) from a location_id/hrd_location_id/name. At the moment, `hydra_ring.locations.Location` expects integer pointers to some internal process but these numbers are relatively arbitrary.
- [ ] `project.get_locations()` works well, but is quite slow. Is this due to reading all databases or does it happen with finding the nearest locations? The latter can be done super quick with a KDTree. It would in principle also be fine if there is a method instead that provides the location_id/name/x/y for all available locations in the hlcd, I can easily create a KDTree myself.
- [ ] when getting a location_id from the list returned by project.get_locations, this is an integer. However, `project.settings.location_id` has to be a string. Would be useful to align the returned/expected type.
- [ ] hoek van holland takes >1 minute, while lobith/harlingen/vlissingen take 10-15 seconds. Is this expected?
- [ ] the config settings should come from `project.settings.read_from_config()`. However, when checking this with one of the config files, the settings were the same as the default hydra_ring settings. Is this working properly? It could be a coincidence, but the printed settings in the [get_config_settings.ipynb](https://github.com/Deltares/Hydra-Ring/blob/main/wrapper/HydraRing.PWrapper.Notebooks/get_config_settings.ipynb) notebook are also the same as the hydra_ring default settings (except for Calculation Technique)
- [ ] These points are also documented in https://github.com/Deltares/Hydra-Ring/issues/215

Some improvement ideas for the database/settings:
- request a single hlcd file (and maybe one config file) for the entire NL at RWS
- request direct download links instead of stack download buttons that use expiring tokens
