### ISSUE TITLE
Create 0.2.0 release

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares-research/kenmerkendewaarden#21]
The goal of this tag/release is to reduce the complexity for the user by making the public functions straightforward to use. There will be no changes that significantly affect the results, so we can still (approximately) reproduce the kenmerkendewaarden 2011/2021 derived in 2020-2022. The resulting methods are still not production-ready, since there are still improvements needed that will be inplemented in [kenmerkendewaarden 0.3.0](https://github.com/Deltares-research/kenmerkendewaarden/issues/75).

Todo:
- [x] https://github.com/Deltares-research/kenmerkendewaarden/issues/5
- [x] https://github.com/Deltares-research/kenmerkendewaarden/issues/12
- [x] convert all onenote notes to issues
- [x] add to readme description: https://www.rijkswaterstaat.nl/water/waterbeheer/metingen/meten-bij-rijkswaterstaat/waternormalen#:~:text=Kenmerkende%20waarden%20zijn%20voor%20veel,laatste%20jaar%20is%20onvoldoende%20representatief. (And more online references)
- [x] add warning: still under development, release will contain official version
- [x] https://github.com/Deltares-research/kenmerkendewaarden/issues/27
- [x] https://github.com/Deltares-research/kenmerkendewaarden/issues/30
- [x] https://github.com/Deltares-research/kenmerkendewaarden/issues/35
- [x] https://github.com/Deltares-research/kenmerkendewaarden/issues/32
- [x] increase test coverage
- [x] https://github.com/Deltares-research/kenmerkendewaarden/issues/58
- [x] https://github.com/Deltares-research/kenmerkendewaarden/issues/77
- [x] gemgetij: validation data is not in timedelta so cannot be compared with new timedelta axis
- [x] link issues that are not yet linked to release issue (or link to 0.3.0 issue)
- [x] https://github.com/Deltares-research/kenmerkendewaarden/issues/26
- [x] create issues from all TODO in `KWK_process.py` and underlying functions
- [x] https://github.com/Deltares-research/kenmerkendewaarden/issues/83
- [x] https://github.com/Deltares-research/kenmerkendewaarden/issues/82
- [x] https://github.com/Deltares-research/kenmerkendewaarden/issues/90
- [x] https://github.com/Deltares-research/kenmerkendewaarden/issues/92
- [x] https://github.com/Deltares-research/kenmerkendewaarden/issues/94
- [x] add additional logging info messages in modules
- [x] #97
- [x] #99
- [x] https://github.com/Deltares-research/kenmerkendewaarden/issues/39
- [x] https://github.com/Deltares-research/kenmerkendewaarden/issues/95
- [x] https://github.com/Deltares-research/kenmerkendewaarden/issues/17
- [x] derive preliminary output 2011 and 2021 for `station_list = ["VLISSGN","HOEKVHLD","IJMDBTHVN","HARLGN","DENHDR","DELFZL","SCHIERMNOG","VLIELHVN","STELLDBTN","SCHEVNGN","ROOMPBTN"]`
- [x] https://github.com/Deltares-research/kenmerkendewaarden/issues/114
- [x] https://github.com/Deltares-research/kenmerkendewaarden/issues/115
- [x] https://github.com/Deltares-research/kenmerkendewaarden/issues/118
- [x] if re-retrieving data, also update timezone of tstart/tstop: https://github.com/Deltares-research/kenmerkendewaarden/issues/120
- [x] re-retrieve data to get smaller filesizes after https://github.com/Deltares-research/kenmerkendewaarden/issues/118
- [x] https://github.com/Deltares-research/kenmerkendewaarden/issues/122
- [x] https://github.com/Deltares-research/kenmerkendewaarden/issues/125
- [x] https://github.com/Deltares-research/kenmerkendewaarden/issues/111
- [x] #128
- [x] #130
- [x] derive kenmerkendewaarden for 2011 and 2021 and compare results

Tasks not related to methods (maybe partly for next tag/release):
- [x] report `TimeSeries_TimedeltaFormatter_improved` to pandas >> commented in https://github.com/pandas-dev/pandas/issues/17232#issuecomment-2205579156
- [x] #112
- [x] https://github.com/Deltares/hatyan/issues/272 >> very present when using `pandas>=2.2.0`
- [x] check warnings in pytest workflow: https://github.com/Deltares/hatyan/issues/319
- [x] fix "metodieken" typo in readme
- [x] consider updating whatsnew for PR's between 87 and 116
- [ ] tag+release v0.2.0
- [ ] release on pypi and add supported-py-versions badge and pypi-package-version badge and number-of-downloads badge. Maybe move to 0.3.0 release? Will AB use tidalindicators etc?
- [ ] produce 2011/2021 results, zip+backup files and send to RWS

Follow-up: https://github.com/Deltares-research/kenmerkendewaarden/issues/75
